### ISSUE TITLE
Open Source this project

### ISSUE THREAD

**Issue by dbrajkovic** [mikera/randomz#1]
As is, all rights of this project still belong to the author.  It is a violation of copyright law to reproduce, etc this code without the express permission of the author.  Please attach an open source license so that everyone can use this code.

**Comment by mikera** [comment]
OK will do. Any preference for license? I'm thinking dual EPL + LGPL

**Comment by dbrajkovic** [comment]
Anything except any form of GPL. MIT is good.

**Comment by mikera** [comment]
Now available under MIT license
